pipeline {
 agent any
 stages {
        stage("Build") {
            steps {
                sh 'composer install'
                sh 'cp .env.example .env'
                sh 'php artisan key:generate'
                sh 'npm install'
                sh 'npm run prod'
            }
        }
        stage("Unit test") {
            steps {
                sh 'php artisan test'
            }
        }
        stage("Deliver") {
            steps {
                sh 'php artisan serve -p=3000 & sleep 1'
                sh 'echo $! > .pidfile'
            }
        }

   }
}