pipeline {
 agent any
 stages {
        stage("Build") {
            steps {
                sh 'composer install'
                sh 'cp .env.example .env'
                sh 'php artisan key:generate'
                sh 'npm install'
                sh 'npm run prod'
            }
        }
        stage("Unit test") {
            steps {
                sh 'php artisan test'
            }
        }
   }
}