pipeline {
 agent any
 stages {
        stage("Build") {
            steps {
                sh 'composer install'
                sh 'cp .env.example .env'
                sh 'php artisan key:generate'
                sh 'npm install'
                sh 'npm run prod'
            }
        }
        stage("Unit test") {
            steps {
                sh 'php artisan test'
            }
        }
        stage("Deploy") {
            steps {
                sh 'ssh radcloud@51.222.32.200'
                sh 'cd /var/www/html/laravel && git pull origin master'
            }
        }
   }
}